### ISSUE TITLE
How to properly install jfxswt.jar?

### ISSUE THREAD

**Issue by scharf** [JanKoehnlein/JavaFX-SWT-Gesture-Bridge#1]
In order to run the Demo, I had to add `.../jre/lib/jfxswt.jar` manually to the "Java Build Path" as external jar. Is this the expected way to get access to `javafx.embed.swt.FXCanvas`.

I tried to add `jfxswt.jar` to the JSE in "Installed JREs", but then there seems to be a [class loading order problem](http://stackoverflow.com/a/20237472/2297345):

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Canvas
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.fxdiagram.swtfx.Demo.main(Demo.java:58)
```

**Comment by JanKoehnlein** [comment]
The `swtfx.jar` should be automatically added to the boot classpath by e(fx)clipse but I have also experienced that it didn't work until I added the VM argument
`-Dosgi.framework.extensions=org.eclipse.fx.osgi` to the launch config that spawns he runtime Eclipse. If that doesn't work, make also sure `org.eclipse.fx.osgi` is in the target platform.

The problem is that FXCanvas depends on SWT, but as part of the JRE resides on the extension classpath. This is what is solved by `org.eclipse.fx.osgi` by hooking into the OSGi classpath setup.
